apiVersion: v1
kind: Service
metadata:
  name: pyflask_api-service
spec:
  selector:
    app: pyflask_api
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyflask_api
spec:
  selector:
    matchLabels:
      app: pyflask_api
  replicas: 2
  template:
    metadata:
      labels:
        app: pyflask_api
    spec:
      containers:
      - name: pyflask_api
        image: piyush9090/pyflask_api
        imagePullPolicy: Always
        ports:
        - containerPort: 5000