apiVersion: v1
kind: Service
metadata:
  name: pyflask-service
spec:
  selector:
    app: pyflask
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyflask
spec:
  selector:
    matchLabels:
      app: pyflask
  replicas: 2
  template:
    metadata:
      labels:
        app: pyflask
    spec:
      containers:
      - name: pyflask
        image: piyush9090/pyflask_api
        imagePullPolicy: Always
        ports:
        - containerPort: 5000